
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox1;

	private global::Gtk.Label label1;

	private global::Gtk.Entry txthost;

	private global::Gtk.Label label2;

	private global::Gtk.Entry txtDir;

	private global::Gtk.CheckButton chkanon;

	private global::Gtk.Label label3;

	private global::Gtk.Entry txtUser;

	private global::Gtk.Label label4;

	private global::Gtk.Entry txtPass;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button btnOk;

	private global::Gtk.Button btnCancel;

	private global::Gtk.VBox vbox2;

	private global::Gtk.ScrolledWindow scrolledwindow2;

	private global::Gtk.TreeView tvls;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button btnDown;

	private global::Gtk.CheckButton chkLs;

	private global::Gtk.HBox hbox4;

	private global::Gtk.RadioButton rbascii;

	private global::Gtk.RadioButton rbbin;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Simple FTP");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 666;
		this.DefaultHeight = 350;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Servidor");
		this.vbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.txthost = new global::Gtk.Entry ();
		this.txthost.CanFocus = true;
		this.txthost.Name = "txthost";
		this.txthost.IsEditable = true;
		this.txthost.InvisibleChar = '●';
		this.vbox1.Add (this.txthost);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.txthost]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Directorio en el servidor");
		this.vbox1.Add (this.label2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label2]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.txtDir = new global::Gtk.Entry ();
		this.txtDir.CanFocus = true;
		this.txtDir.Name = "txtDir";
		this.txtDir.IsEditable = true;
		this.txtDir.InvisibleChar = '●';
		this.vbox1.Add (this.txtDir);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.txtDir]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.chkanon = new global::Gtk.CheckButton ();
		this.chkanon.CanFocus = true;
		this.chkanon.Name = "chkanon";
		this.chkanon.Label = global::Mono.Unix.Catalog.GetString ("Autenticación anónima");
		this.chkanon.DrawIndicator = true;
		this.chkanon.UseUnderline = true;
		this.vbox1.Add (this.chkanon);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.chkanon]));
		w5.Position = 4;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Usuario");
		this.vbox1.Add (this.label3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label3]));
		w6.Position = 5;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.txtUser = new global::Gtk.Entry ();
		this.txtUser.CanFocus = true;
		this.txtUser.Name = "txtUser";
		this.txtUser.IsEditable = true;
		this.txtUser.InvisibleChar = '●';
		this.vbox1.Add (this.txtUser);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.txtUser]));
		w7.Position = 6;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
		this.vbox1.Add (this.label4);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label4]));
		w8.Position = 7;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.txtPass = new global::Gtk.Entry ();
		this.txtPass.CanFocus = true;
		this.txtPass.Name = "txtPass";
		this.txtPass.IsEditable = true;
		this.txtPass.Visibility = false;
		this.txtPass.InvisibleChar = '●';
		this.vbox1.Add (this.txtPass);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.txtPass]));
		w9.Position = 8;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnOk = new global::Gtk.Button ();
		this.btnOk.CanFocus = true;
		this.btnOk.Name = "btnOk";
		this.btnOk.UseStock = true;
		this.btnOk.UseUnderline = true;
		this.btnOk.Label = "gtk-ok";
		this.hbox2.Add (this.btnOk);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnOk]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnCancel = new global::Gtk.Button ();
		this.btnCancel.CanFocus = true;
		this.btnCancel.Name = "btnCancel";
		this.btnCancel.UseStock = true;
		this.btnCancel.UseUnderline = true;
		this.btnCancel.Label = "gtk-quit";
		this.hbox2.Add (this.btnCancel);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnCancel]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w12.Position = 9;
		w12.Expand = false;
		w12.Fill = false;
		this.hbox1.Add (this.vbox1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow2.CanFocus = true;
		this.scrolledwindow2.Name = "scrolledwindow2";
		this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow2.Gtk.Container+ContainerChild
		this.tvls = new global::Gtk.TreeView ();
		this.tvls.CanFocus = true;
		this.tvls.Name = "tvls";
		this.tvls.EnableSearch = false;
		this.scrolledwindow2.Add (this.tvls);
		this.vbox2.Add (this.scrolledwindow2);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.scrolledwindow2]));
		w15.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnDown = new global::Gtk.Button ();
		this.btnDown.CanFocus = true;
		this.btnDown.Name = "btnDown";
		this.btnDown.UseStock = true;
		this.btnDown.UseUnderline = true;
		this.btnDown.Label = "gtk-save";
		this.hbox3.Add (this.btnDown);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnDown]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.chkLs = new global::Gtk.CheckButton ();
		this.chkLs.CanFocus = true;
		this.chkLs.Name = "chkLs";
		this.chkLs.Label = global::Mono.Unix.Catalog.GetString ("Listado detallado");
		this.chkLs.DrawIndicator = true;
		this.chkLs.UseUnderline = true;
		this.hbox3.Add (this.chkLs);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.chkLs]));
		w17.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.rbascii = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("ASCII"));
		this.rbascii.CanFocus = true;
		this.rbascii.Name = "rbascii";
		this.rbascii.DrawIndicator = true;
		this.rbascii.UseUnderline = true;
		this.rbascii.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.hbox4.Add (this.rbascii);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.rbascii]));
		w18.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.rbbin = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Binario"));
		this.rbbin.CanFocus = true;
		this.rbbin.Name = "rbbin";
		this.rbbin.DrawIndicator = true;
		this.rbbin.UseUnderline = true;
		this.rbbin.Group = this.rbascii.Group;
		this.hbox4.Add (this.rbbin);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.rbbin]));
		w19.Position = 1;
		this.hbox3.Add (this.hbox4);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hbox4]));
		w20.Position = 2;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
		w22.Position = 1;
		this.Add (this.hbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.chkanon.Toggled += new global::System.EventHandler (this.OnChkanonToggled);
		this.btnOk.Clicked += new global::System.EventHandler (this.OnBtnOkClicked);
		this.btnCancel.Clicked += new global::System.EventHandler (this.OnBtnCancelClicked);
		this.btnDown.Clicked += new global::System.EventHandler (this.OnBtnDownClicked);
		this.chkLs.Toggled += new global::System.EventHandler (this.OnChkLsToggled);
	}
}
